[package]
name = "mop-watch"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mop-core = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
