[package]
name = "mop-plugin-manga"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mop-plugin-sdk = { workspace = true }
mop-plugin-common = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tempfile = { workspace = true }
anyhow = "1.0"
notify = "8.2"
libarchive2 = "0.2.1"
libvips = "2.3.0"
walkdir = "2.5"
zip = { version = "8.6.0", default-features = false }
chrono = { workspace = true }
